app <- ShinyDriver$new("../", loadTimeout = 120000)
app$snapshotInit("mytest")

app$setInputs(sidebarCollapsed = FALSE)
Sys.sleep(10)
app$setInputs(PlotOpts = "Mass shifts")
app$setInputs(PlotOpts = "RT correction")
app$setInputs(PlotOpts = "Molecular formula prediction")
app$setInputs(EICplots = "Regroup MS data")
Sys.sleep(5)
app$setInputs(EICplots = "MS Browser")
Sys.sleep(5)
app$setInputs(EICplots = "Quickplots")
app$setInputs(EICplots = "MS2 Browser")
Sys.sleep(5)
app$setInputs(TableBox = "Analyze Table")
app$setInputs(TableBox = "View Table")
Sys.sleep(15)
app$snapshot()
