app <- ShinyDriver$new("../", loadTimeout = 120000)
app$snapshotInit("mytest")

app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(PlotOpts = "Mass shifts")
app$setInputs(PlotOpts = "RT correction")
app$setInputs(PlotOpts = "Molecular formula prediction")
app$setInputs(EICplots = "Regroup MS data")
app$setInputs(EICplots = "MS Browser")
app$setInputs(EICplots = "Quickplots")
app$setInputs(EICplots = "MS2 Browser")
app$setInputs(TableBox = "Analyze Table")
app$setInputs(TableBox = "View Table")
app$snapshot()
